#!/bin/bash

# Script to analyze and visualize dependencies between source files

echo "═══════════════════════════════════════════════════════════"
echo "  C++ Module Dependency Analyzer"
echo "═══════════════════════════════════════════════════════════"
echo

# Function to extract local includes (our headers)
analyze_file() {
    local file=$1
    local basename=$(basename "$file" .cpp)
    
    echo "📄 $file"
    echo "   Dependencies:"
    
    # Extract all local includes (quotes, not angle brackets)
    grep '^#include "' "$file" | sed 's/#include "\(.*\)"/   → \1/' | sort -u
    echo
}

echo "╔════════════════════════════════════════════════════════╗"
echo "║  Source File Dependencies (Direct includes only)       ║"
echo "╚════════════════════════════════════════════════════════╝"
echo

for file in src/*.cpp; do
    analyze_file "$file"
done

echo
echo "╔════════════════════════════════════════════════════════╗"
echo "║  Dependency Graph (generated by g++ -MM)               ║"
echo "╚════════════════════════════════════════════════════════╝"
echo

for file in src/*.cpp; do
    echo "$(basename "$file" .cpp).o:"
    g++ -std=c++17 -Isrc -MM "$file" | sed '1d' | sed 's/^ */  /'
    echo
done

echo
echo "╔════════════════════════════════════════════════════════╗"
echo "║  Module Usage Count (how many files include each)     ║"
echo "╚════════════════════════════════════════════════════════╝"
echo

echo "Header File           | Included By (count)"
echo "----------------------|-------------------"

for header in src/*.h; do
    hname=$(basename "$header")
    count=$(grep -l "\"$hname\"" src/*.cpp 2>/dev/null | wc -l | tr -d ' ')
    printf "%-20s | %d files\n" "$hname" "$count"
done | sort -t'|' -k2 -rn

echo
echo "╔════════════════════════════════════════════════════════╗"
echo "║  Circular Dependency Check                             ║"
echo "╚════════════════════════════════════════════════════════╝"
echo

# Check for potential circular dependencies in headers
echo "Checking for #include statements in headers that might cause circular deps..."
echo

for header in src/*.h; do
    hname=$(basename "$header")
    includes=$(grep '^#include "' "$header" | wc -l | tr -d ' ')
    if [ "$includes" -gt 0 ]; then
        echo "$hname includes:"
        grep '^#include "' "$header" | sed 's/#include "\(.*\)"/  → \1/'
    fi
done

echo
echo "✓ Analysis complete!"
echo
